# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mentore.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mentorePalette import mentorePaletteSetter
import addMentore


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(MainWindow, self).__init__()

        self.setObjectName("MainWindow")
        self.resize(800, 480)

        palette = QtGui.QPalette()
        palette = mentorePaletteSetter(palette)
        self.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(150, 50, 351, 81))
        self.mainLabel.setObjectName("mainLabel")
        self.recentLabel = QtWidgets.QLabel(self.centralwidget)
        self.recentLabel.setGeometry(QtCore.QRect(60, 180, 141, 51))
        self.recentLabel.setObjectName("recentLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 250, 160, 106))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.recentVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.recentVLayout.setContentsMargins(0, 0, 0, 0)
        self.recentVLayout.setObjectName("recentVLayout")
        self.recent1_pb = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.recent1_pb.setObjectName("recent1_pb")
        self.recentVLayout.addWidget(self.recent1_pb)
        self.recent2_pb = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.recent2_pb.setObjectName("recent2_pb")
        self.recentVLayout.addWidget(self.recent2_pb)
        self.recent3_pb = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.recent3_pb.setObjectName("recent3_pb")
        self.recentVLayout.addWidget(self.recent3_pb)
        self.browse_pb = QtWidgets.QPushButton(self.centralwidget)
        self.browse_pb.setGeometry(QtCore.QRect(460, 240, 106, 30))
        self.browse_pb.setObjectName("browse_pb")
        self.add_pb = QtWidgets.QPushButton(self.centralwidget)
        self.add_pb.setGeometry(QtCore.QRect(460, 290, 106, 30))
        self.add_pb.setObjectName("add_pb")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar()
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Mentore"))
        self.mainLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Select the class/subject to edit</p></body></html>"))
        self.recentLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Recently used</p></body></html>"))
        self.recent1_pb.setText(_translate("MainWindow", "recent 1"))
        self.recent2_pb.setText(_translate("MainWindow", "recent 2"))
        self.recent3_pb.setText(_translate("MainWindow", "recent 3"))
        self.browse_pb.setText(_translate("MainWindow", "Browse"))
        self.add_pb.setText(_translate("MainWindow", "Add"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

        self.setWindowIcon(QtGui.QIcon('images/mentore_logo.svg'))

        self.connect_events()

    def connect_events(self):

        # Add TODO push button
        self.add_pb.clicked.connect(lambda: addMentore.addWindow().show())


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    mentoreWindow = MainWindow()

    mentoreWindow.show()
    sys.exit(app.exec_())
