# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addConcept.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mentorePalette import mentorePaletteSetter



class addConceptDialog(QtWidgets.QDialog):

    def __init__(self):
        super(addConceptDialog, self).__init__()

        self.setObjectName("conceptDialog")
        self.resize(640, 480)

        palette = QtGui.QPalette()
        palette = mentorePaletteSetter(palette)
        self.setPalette(palette)

        self.buttonBox = QtWidgets.QDialogButtonBox()
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit()
        self.lineEdit.setGeometry(QtCore.QRect(250, 200, 161, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel()
        self.label.setGeometry(QtCore.QRect(120, 50, 471, 141))
        self.label.setObjectName("label")

        self.retranslateUi()
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("conceptDialog", "Add concept"))
        self.label.setText(_translate("conceptDialog", "<html><head/><body><p align=\"center\">here we need to be able to select name</p><p align=\"center\">of the concept and its position inside schoolSubject</p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    conceptDialog = addConceptDialog()

    conceptDialog.show()
    sys.exit(app.exec_())
