# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


def addLayout(mWindow):
    mWindow.centralwidget = QtWidgets.QWidget()
    mWindow.centralwidget.setObjectName("centralwidget")
    mWindow.mainLabel = QtWidgets.QLabel(mWindow.centralwidget)
    mWindow.mainLabel.setGeometry(QtCore.QRect(150, 50, 351, 81))
    mWindow.mainLabel.setObjectName("mainLabel")
    mWindow.verticalLayoutWidget = QtWidgets.QWidget(mWindow.centralwidget)
    mWindow.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 285, 160, 71))
    mWindow.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
    mWindow.addVLayout = QtWidgets.QVBoxLayout(mWindow.verticalLayoutWidget)
    mWindow.addVLayout.setContentsMargins(0, 0, 0, 0)
    mWindow.addVLayout.setObjectName("addVLayout")
    mWindow.addSentence_pb = QtWidgets.QPushButton(mWindow.verticalLayoutWidget)
    mWindow.addSentence_pb.setObjectName("addSentence_pb")
    mWindow.addVLayout.addWidget(mWindow.addSentence_pb)
    mWindow.addQuestion_pb = QtWidgets.QPushButton(mWindow.verticalLayoutWidget)
    mWindow.addQuestion_pb.setObjectName("addQuestion_pb")
    mWindow.addVLayout.addWidget(mWindow.addQuestion_pb)
    mWindow.back_pb = QtWidgets.QPushButton(mWindow.centralwidget)
    mWindow.back_pb.setGeometry(QtCore.QRect(510, 380, 106, 30))
    mWindow.back_pb.setObjectName("back_pb")
    mWindow.setCentralWidget(mWindow.centralwidget)
    mWindow.menubar = QtWidgets.QMenuBar()
    mWindow.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
    mWindow.menubar.setObjectName("menubar")
    mWindow.menuHelp = QtWidgets.QMenu(mWindow.menubar)
    mWindow.menuHelp.setObjectName("menuHelp")
    mWindow.setMenuBar(mWindow.menubar)
    mWindow.statusbar = QtWidgets.QStatusBar()
    mWindow.statusbar.setObjectName("statusbar")
    mWindow.setStatusBar(mWindow.statusbar)
    mWindow.menubar.addAction(mWindow.menuHelp.menuAction())

    #mWindow.retranslateUi()
    QtCore.QMetaObject.connectSlotsByName(mWindow)

#def retranslateUi(mWindow):
    _translate = QtCore.QCoreApplication.translate
    mWindow.setWindowTitle(_translate("addWindow", "Mentore"))
    mWindow.mainLabel.setText(_translate("addWindow", "<html><head/><body><p align=\"center\">Something goes here...</p></body></html>"))
    mWindow.addSentence_pb.setText(_translate("addWindow", "Add sentence"))
    mWindow.addQuestion_pb.setText(_translate("addWindow", "Add question"))
    mWindow.back_pb.setText(_translate("addWindow", "< Back"))
    mWindow.menuHelp.setTitle(_translate("addWindow", "Help"))

    return mWindow
