# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mentorePalette import mentorePaletteSetter


class addWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(addWindow, self).__init__()

        self.setObjectName("addWindow")
        self.resize(800, 480)

        palette = QtGui.QPalette()
        palette = mentorePaletteSetter(palette)
        self.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(150, 50, 351, 81))
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 285, 160, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.addVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.addVLayout.setContentsMargins(0, 0, 0, 0)
        self.addVLayout.setObjectName("addVLayout")
        self.addSentence_pb = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addSentence_pb.setObjectName("addSentence_pb")
        self.addVLayout.addWidget(self.addSentence_pb)
        self.addQuestion_pb = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addQuestion_pb.setObjectName("addQuestion_pb")
        self.addVLayout.addWidget(self.addQuestion_pb)
        self.back_pb = QtWidgets.QPushButton(self.centralwidget)
        self.back_pb.setGeometry(QtCore.QRect(510, 380, 106, 30))
        self.back_pb.setObjectName("back_pb")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar()
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())
    
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("addWindow", "Mentore"))
        self.mainLabel.setText(_translate("addWindow", "<html><head/><body><p align=\"center\">Something goes here...</p></body></html>"))
        self.addSentence_pb.setText(_translate("addWindow", "Add sentence"))
        self.addQuestion_pb.setText(_translate("addWindow", "Add question"))
        self.back_pb.setText(_translate("addWindow", "< Back"))
        self.menuHelp.setTitle(_translate("addWindow", "Help"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    add_Window = addWindow()

    add_Window.show()
    sys.exit(app.exec_())
